# CS 416 - Intro to Deep Learning
## Assignment 1

---

**Name** : Syed Muhammad Ashhar Shah

**Reg No** : 2020478

# Task 2

## Importing the required libraries.

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split

2023-10-15 11:47:42.972878: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-15 11:47:43.061486: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-15 11:47:43.061558: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-15 11:47:43.061632: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-15 11:47:43.075853: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-15 11:47:44.710847: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT

## Getting the dataset from the URL

In [2]:
dataset = "./train.csv"

In [3]:
df = pd.read_csv(dataset)

In [4]:
df.head(5)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

### Selecting Specific Columns
Only using those columns that contain numerical values to make predictions using the linear regression algorithm.

In [5]:
data = df[["MSSubClass", "LotFrontage", "LotArea", "YrSold", "SalePrice"]]

In [6]:
data.head(5)

MSSubClass  LotFrontage  LotArea  YrSold  SalePrice
0          60         65.0     8450    2008     208500
1          20         80.0     9600    2007     181500
2          60         68.0    11250    2008     223500
3          70         60.0     9550    2006     140000
4          60         84.0    14260    2008     250000

In [7]:
data = data.dropna()

In [8]:
data.dropna()

MSSubClass  LotFrontage  LotArea  YrSold  SalePrice
0             60         65.0     8450    2008     208500
1             20         80.0     9600    2007     181500
2             60         68.0    11250    2008     223500
3             70         60.0     9550    2006     140000
4             60         84.0    14260    2008     250000
...          ...          ...      ...     ...        ...
1254          60         60.0     6931    2008     165400
1255          50         52.0     6240    2007     127500
1256          20         91.0    14303    2008     301500
1257          30         56.0     4060    2009      99900
1258          80         59.0     9587    2008     190000

[1041 rows x 5 columns]

## Converting the dataset to numpy array

In [9]:
dataset_array = np.array(data, dtype=float)
print("Dataset Array Shape: " + str(dataset_array.shape))


X = []
y = []

for row in dataset_array:
  X.append(row[:4])
  y.append(row[4])


X = np.array(X)
y = np.array(y)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

print("X Shape: " + str(X.shape))
print("y Shape: " + str(y.shape))

Dataset Array Shape: (1041, 5)
X Shape: (1041, 4)
y Shape: (1041,)


## Function For Forward Propogation

In [10]:
def forward_prop(w, x):
  y = []
  for row in x:
    y.append(w[0] + row[0]*w[1] + row[1]*w[2] + row[2]*w[3] + row[3]*w[4])

  y = np.array(y)
  return y

## Function For Backward Propogation

In [11]:
def back_prop(w, y, y_hat, X, alpha):
  # get the total number of rows
  n = y.shape[0]
  # create an error against each weight value
  dldw = np.zeros(*w.shape)

  for predict, actual, x in zip(y,y_hat,X):
    error = actual - predict
    dldw[0] = dldw[0] + ((error))
    dldw[1] = dldw[1] + ((error) * x[0])
    dldw[2] = dldw[2] + ((error) * x[1])
    dldw[3] = dldw[3] + ((error) * x[2])
    dldw[4] = dldw[4] + ((error) * x[3])

  w[0] = w[0] + (dldw[0] * alpha)/n
  w[1] = w[1] + (dldw[1] * alpha)/n
  w[2] = w[2] + (dldw[2] * alpha)/n
  w[3] = w[3] + (dldw[3] * alpha)/n
  w[4] = w[4] + (dldw[4] * alpha)/n

  return w

## Getting the testing dataset

In [12]:
test_dataset = './test.csv'
test_df = pd.read_csv(test_dataset)

In [13]:
test_df.head(5)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1260          20       RL         65.0     9750   Pave   NaN      Reg   
1  1261          60       RL          NaN    24682   Pave   NaN      IR3   
2  1262          20       RL         80.0     9600   Pave   NaN      Reg   
3  1263          50       RL          NaN    11250   Pave   NaN      Reg   
4  1264          70       RL         60.0    13515   Pave  Pave      Reg   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...          80        0    NaN    NaN         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
2         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         Lvl    AllPub  ...           0        0    NaN  GdPrv         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      7    2008        WD         Normal  
1       0      6    2009        WD         Normal  
2       0      6    2009        WD         Normal  
3       0     11    2009        WD         Normal  
4       0      7    2007        WD         Normal  

[5 rows x 80 columns]

In [14]:
test_data = test_df[["MSSubClass", "LotFrontage", "LotArea", "YrSold"]]

In [15]:
test_data.head(5)

MSSubClass  LotFrontage  LotArea  YrSold
0          20         65.0     9750    2008
1          60          NaN    24682    2009
2          20         80.0     9600    2009
3          50          NaN    11250    2009
4          70         60.0    13515    2007

In [16]:
test_data = test_data.dropna()

### Converting to Numpy Arrays

In [17]:
test_dataset_array = np.array(test_data, dtype=float)
print("Dataset Array Shape: " + str(test_dataset_array.shape))


test_X = []

for row in test_dataset_array:
  test_X.append(row[:4])


test_X = np.array(test_X)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
test_X = scaler.fit_transform(test_X)

print("Test X Shape: " + str(test_X.shape))

Dataset Array Shape: (160, 4)
Test X Shape: (160, 4)


## Cost Function

In [18]:
def cost(y, y_hat):
  n = y.shape[0]

  sum = 0

  for predict, actual in zip(y, y_hat):
    sum = sum + (predict - actual)**2

  j = sum / (2 * n)

  return j

## Carrying out the learning ( **Batch Gradient Descent** )

### Initialize random weights

In [19]:
weights = np.random.rand(X.shape[1] + 1)

print("Shape of weights: " + str(weights.shape))
print("Random Weights: " + str(weights))

Shape of weights: (5,)
Random Weights: [0.09096607 0.68308742 0.7077221  0.84144394 0.9927101 ]


### Perfoming Forward and Backward Propgations

In [20]:
costs = []

costs.append(cost(weights, y))

for epoch in range(1000):
  hx = forward_prop(weights, X)
  c = cost(hx, y)
  if epoch % 100 == 0:
    print("Cost: " +str(c))

  costs.append(c)
  weights = back_prop(weights, hx, y, X, 0.01)

Cost: 20129991317.86173


Cost: 5248402300.176957
Cost: 3282386405.1507697
Cost: 3015586046.7726192
Cost: 2978353744.2379723
Cost: 2972869327.309001
Cost: 2971969607.0789614
Cost: 2971793536.7715693
Cost: 2971751079.987927
Cost: 2971738944.9427547


### Final Weights For Our Params

In [21]:
weights

array([181645.07808974,   6679.9333452 ,  28268.75947672,  16899.11756272,
        -3056.93204568])

### Making Predictions

In [22]:
batch_predict = forward_prop(weights, test_X)

In [23]:
batch_predict

array([171384.44900841, 183395.39532501, 187839.29851472, 139097.03542991,
       149827.48000565, 196054.32201216, 200889.411119  , 195892.72632896,
       243967.59239432, 153220.39220811, 218772.19526938, 186540.23191969,
       159714.88054222, 171241.7301921 , 156060.54983785, 162293.72345556,
       205052.95729469, 156347.60659842, 147630.56045144, 147562.73084428,
       206740.10510997, 122992.90836577, 162358.17652706, 196076.53359656,
       166265.34752844, 176787.67728158, 182958.37572324, 152726.34869939,
       585115.81020725, 169843.65450256, 209782.01548318, 180608.47183547,
       145752.65980173, 221732.48616467, 166187.17977868, 159108.8846659 ,
       212603.61795214, 224666.88221678, 173788.41073896, 230450.04147153,
       164035.09780484, 201217.69551984, 166606.11127641, 154678.49977945,
       184908.1777799 , 169933.62590717, 215592.11923975, 142524.08789429,
       184215.65547206, 129853.08951653, 163553.55682333, 156942.07135198,
       173175.1458764 , 1

## Carrying out the learning ( **Mini-Batch Gradient Descent** )

### Initialize Random Weights

In [24]:
weights = np.random.rand(X.shape[1] + 1)

print("Shape of weights: " + str(weights.shape))
print("Random Weights: " + str(weights))

Shape of weights: (5,)
Random Weights: [0.16191571 0.16246986 0.4826512  0.48869728 0.71524603]


### Initialize Batches

In [25]:
batchSize = 300

batches_X = []
batches_y = []

for i in range(X.shape[0] // batchSize):
    batches_X.append(X[300*i : 300*(i+1)])
    batches_y.append(y[300*i : 300*(i+1)])

batches_X = np.array(batches_X)
batches_y = np.array(batches_y)


print("Shape Of Batches X: " + str(batches_X.shape))
print("Shape Of Batches y: " + str(batches_y.shape))

Shape Of Batches X: (3, 300, 4)
Shape Of Batches y: (3, 300)


### Perform Forward and Backward Propogations

In [26]:
costs = []

costs.append(cost(weights, y))

# interate over the whole dataset
for epoch in range(1000):
  # for every batch perform forward and backward propogation
  for batchx,batchy in zip(batches_X,batches_y):
    # forward propogation
    hx = forward_prop(weights, batchx)
    # backward propogation
    weights = back_prop(weights, hx, batchy, batchx, 0.01)
  

  # get cost against each epoch after a batch completes
  c = cost(hx, y)
  # print cost per 100 epoch
  if epoch % 100 == 0:
    print("Cost: " +str(c))
  # append cost to list
  costs.append(c)

Cost: 20070104005.88807


Cost: 3834445177.286156
Cost: 3785250441.68632
Cost: 3790764019.2061677
Cost: 3792322582.8239884
Cost: 3792662916.5514297
Cost: 3792733908.9939256
Cost: 3792748569.046009
Cost: 3792751589.42354
Cost: 3792752211.380592


In [27]:
weights

array([182370.57703046,   5399.94873517,  27026.57774312,  15831.13296188,
        -3411.21361518])

### Making Predictions

In [28]:
mini_batch_predict = forward_prop(weights, test_X)

In [29]:
mini_batch_predict

array([173376.87580972, 184503.59812708, 188117.39134986, 140565.14912331,
       150663.58612675, 193439.8235249 , 200653.26936711, 196398.24186083,
       241303.32450721, 155949.35159733, 217362.51801189, 186973.04745091,
       160938.43408611, 172871.87538256, 159555.74040237, 164375.75826655,
       203263.86306353, 157594.62492288, 149837.64456317, 148200.26694905,
       206922.94679025, 124032.31509768, 163428.27869232, 196781.81676094,
       169304.95784587, 179351.64007019, 184503.36605193, 152983.68293335,
       564865.85293035, 171304.45711446, 209886.21898305, 182987.77107908,
       146789.48329321, 220948.02402933, 167026.67235277, 161373.2599162 ,
       212653.77656385, 223136.33299057, 176094.88341979, 227914.34100389,
       166806.48576216, 200912.26880707, 168415.61328985, 155817.21112492,
       186644.44458545, 171703.24193177, 213976.4707111 , 145449.45928041,
       185995.68806348, 133799.06816244, 166346.93098591, 159752.55303507,
       174366.38004128, 1

## Carrying out the learning ( **Schotatic Gradient Descent** )

### Initialize Random Weights

In [30]:
weights = np.random.rand(X.shape[1] + 1)

print("Shape of weights: " + str(weights.shape))
print("Random Weights: " + str(weights))

Shape of weights: (5,)
Random Weights: [0.57300589 0.89212504 0.35682841 0.62550921 0.07865025]


### Perform Forward and Backward Propogations

In [31]:
costs = []

# interate over the whole dataset
for epoch in range(100):
  # for every row in data perform forward and backward propogation
  for rowx,rowy in zip(X,y):
    
    # convert to seperate array objects so it can be used by above coded functions
    tempx = []
    tempy = []
    tempx.append(rowx)
    tempy.append(rowy)
    tempx = np.array(tempx)
    tempy = np.array(tempy)

    # perform forward propogation
    hx = forward_prop(weights, tempx)

    # get the cost
    c = cost(hx, y)
    costs.append(c)

    # perform backward propogation
    weights = back_prop(weights, hx, tempy, tempx, 0.01)


In [32]:
for cost in costs[0:100]:
    print("Cost : " + str(cost))

Cost : 21736030678.766148
Cost : 21404802880.598644
Cost : 20998669834.90672
Cost : 20451589366.34598
Cost : 20377301316.87767
Cost : 19822907505.54893
Cost : 19165220331.31761
Cost : 19399802420.350586
Cost : 21257551150.20871
Cost : 18477155785.906013
Cost : 17647736788.827824
Cost : 16356659068.92601
Cost : 17003081829.991621
Cost : 15245942759.691698
Cost : 16667070899.380657
Cost : 17595707779.1655
Cost : 13592511449.313107
Cost : 15293642116.97331
Cost : 15030503474.07896
Cost : 17593242845.852127
Cost : 14464218003.38086
Cost : 17864875657.716145
Cost : 13987056413.843214
Cost : 13286238788.342022
Cost : 13916023247.465034
Cost : 16319921097.235405
Cost : 11226518268.00881
Cost : 13507128709.98234
Cost : 17586573915.16599
Cost : 9224940187.01376
Cost : 8864692703.006056
Cost : 12028072817.202677
Cost : 13203690504.233622
Cost : 14782357296.090425
Cost : 8312523744.127803
Cost : 5701267061.773577
Cost : 8962253275.180216
Cost : 19205590213.416492
Cost : 13854211165.810791
Cost : 

In [33]:
weights

array([179787.35505937,   5115.95408968,  32434.24401099,  32882.72344207,
        -2306.61355325])

### Making Predictions

In [34]:
schotatic_predict = forward_prop(weights, test_X)

In [35]:
schotatic_predict

array([171064.28010656, 185380.30031005, 195199.88250877, 114404.29006675,
       121786.09466806, 189377.06126898, 215076.1576617 , 200372.84674888,
       255072.14009928, 136968.05776417, 224275.90555449, 185434.26660285,
       152274.3735746 , 171938.00856046, 147580.15148557, 159237.49853352,
       206530.84192009, 153573.48836231, 133889.9607491 , 128887.98904247,
       210659.95360015,  88727.50072547, 151061.44595775, 196191.5029858 ,
       159585.66053753, 172209.03137771, 181808.25437442, 123792.14910785,
       774133.02723348, 165658.2882465 , 211868.2343662 , 177288.25642684,
       116212.58018835, 237994.0929836 , 150681.86606598, 153825.48399186,
       223790.22391857, 252706.58832709, 170664.91427356, 250409.33854289,
       157967.6674521 , 206142.80027174, 167628.65005735, 131794.79650305,
       186806.16551784, 167037.29463034, 222283.54778666, 127588.29578168,
       185458.63837972, 108062.30974748, 147362.11461799, 146887.56240993,
       173022.328143  , 1